name: Deploy Spark Job

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rows_count:
        description: 'Количество строк для генерации'
        required: false
        default: '100'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Spark containers are running
        run: docker compose up -d

      - name: Copy main.py into container
        run: docker cp main.py spark-master:/opt/spark/work-dir/main.py

      - name: Run Spark job
        run: docker exec spark-master /opt/spark/bin/spark-submit --master spark://spark-master:7077 /opt/spark/work-dir/main.py --n ${{ github.event.inputs.rows_count || 100 }}