name: Deploy Spark Job

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rows_count:
        description: 'Количество строк для генерации'
        required: false
        default: '100'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install test dependencies
        run: uv sync

      - name: Copy test file into container
        run: docker cp test.py spark-master:/opt/spark/work-dir/test.py

      - name: Install pytest inside container
        run: docker exec spark-master pip install pytest

      - name: Run tests inside container
        run: docker exec spark-master python -m pytest /opt/spark/work-dir/test.py -v

      - name: Wait for MinIO to be ready
        run: Start-Sleep -Seconds 10
        shell: powershell

      - name: Create MinIO bucket if not exists
        run: |
            docker run --rm --network spark-network `
              --entrypoint sh `
              minio/mc `
              -c "mc alias set local http://minio:9000 minioadmin minioadmin && mc mb --ignore-existing local/reports"
        shell: powershell

      - name: Copy main.py into container
        run: docker cp main.py spark-master:/opt/spark/work-dir/main.py

      - name: Run Spark job
        run: docker exec spark-master /opt/spark/bin/spark-submit --master spark://spark-master:7077 --conf spark.jars.ivy=/tmp/.ivy2 --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 /opt/spark/work-dir/main.py --n ${{ github.event.inputs.rows_count || 100 }}